### ISSUE TITLE
Properly document the readme file

### ISSUE THREAD

**Issue by prichoms** [prichoms/pratiroop#1]
The readme file should contain the proper documentation of the project including the aim of the site and the pre-requisites needed.

**Comment by Abhishekchauhan089** [comment]
I would like to work on this project

**Comment by akshitkumar450** [comment]
i would like to contribute..please assign to me

**Comment by prichoms** [comment]
> I would like to work on this project

ya sure @Abhishekchauhan089 you can, but either fork the project and run it on your system, or access the site using the link, and prepare the documentation accordingly.

**Comment by prichoms** [comment]
@akshitkumar450 you too can work on the same issue, if you like, i am assigning to both of you. But plz follow the steps given above first (you ought to know the project first).

**Comment by Abhishekchauhan089** [comment]
@prichoms i have made the PR for Readme file . please check it out
