### ISSUE TITLE
add decent transition to homepage icons   

### ISSUE THREAD

**Issue by prichoms** [prichoms/pratiroop#2]
The icons in the homepage need a transition effect that matches with the background. The already done css code needs to be altered.

**Comment by Abhishekchauhan089** [comment]
i want to work on this issue...can you please add the hackoctober fest label into it..which helps me to increase my Pull request

**Comment by prichoms** [comment]
@Abhishekchauhan089 I have opened these beginner friendly PRs to encourage people for this only. Glad that you are taking the work as long as Hacktoberfest is not the only reason inspiring you to do so.

**Comment by Abhishekchauhan089** [comment]
@prichoms I have made the PR for transtiton to icons
